services:
  payment-notifications:
    image: tedtedted/payment-notifications:latest
    expose:
      - "8081"
    env_file: .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    env_file: .env
    restart: unless-stopped

volumes:
  mongo_data:
